# Book Recommendation System Demo

This notebook demonstrates how to use the recommendation scripts as importable modules.
We will initialize the database connections once and pass them to the various recommendation functions.

## 1. Setup and Database Connection

In [147]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from pymongo import MongoClient
from pymongo.server_api import ServerApi
from importlib import reload

# 1. Setup Path FIRST so Python can find the 'scripts' folder
# Find project root by walking up until a 'scripts' folder is found
PROJECT_ROOT = Path.cwd().parent

# Add project root to system path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# 2. Now you can safely import project modules
import scripts.queries.query_helper 
reload(scripts.queries.query_helper)
from scripts.queries.query_helper import execute_query, QUERIES

# Load environment variables
load_dotenv(PROJECT_ROOT / ".env")

# Database Configuration
db_name = os.getenv("DB_NAME", "bookrec")
host = os.getenv("HOST", "localhost")
msql_user = os.getenv("MSQL_USER")
msql_password = os.getenv("MSQL_PASSWORD")
msql_port = os.getenv("MSQL_PORT", "3306")
mdb_user = os.getenv("MDB_USER")
mdb_password = os.getenv("MDB_PASSWORD")
mdb_cluster = os.getenv("MDB_CLUSTER")
mdb_appname = os.getenv("MDB_APPNAME", "Cluster0")
mdb_port = os.getenv("MDB_PORT", "27017")
mdb_use_atlas = os.getenv("MDB_USE_ATLAS", "false").lower() == "true"

# Initialize MySQL Engine
mysql_engine = create_engine(
    f"mysql+mysqlconnector://{msql_user}:{msql_password}@{host}:{msql_port}/{db_name}"
)

# Initialize MongoDB Client
if mdb_use_atlas:
    mongodb_uri = f"mongodb+srv://{mdb_user}:{mdb_password}@{mdb_cluster}/?retryWrites=true&w=majority&appName={mdb_appname}"
    mongo_client = MongoClient(mongodb_uri, server_api=ServerApi('1'))
else:
    mongodb_uri = f"mongodb://{host}:{mdb_port}/"
    mongo_client = MongoClient(mongodb_uri)

mongo_db = mongo_client[db_name]

print("Database connections established.")

Database connections established.

In [148]:
print("AVAILABLE QUERIES:\n")
print('-' * 50)
for query_type, query_info in QUERIES.items():
    print(f"\n{query_type} Queries:\n")
    if query_type == 'Hybrid':
        # Hybrid structure is flattened (no DB sub-key)
        for query_name, query in query_info.items():
            print(f"   - Query name: {query_name}")
            print(f"   - Query description: {query.get('description')}")
            print(f"     - Query variables: {query.get('variables')}")
            print(f"   - Query {query.get('how')} join, with the keys: {query.get('join_keys')}")
            print(f"   - Databases for join: {{'left': {query['left_query']['db_type']}, 'right': {query['right_query']['db_type']}}}\n")
        print('-' * 50)
        continue
    
    for database, query_meta in query_info.items():
            print(f" - Database: [{database}]\n")
            for query_name, query in query_meta.items():
                print(f"   - Query name: {query_name}")
                print(f"   - Query description: {query.get('description')}")
                print(f"     - Query variables: {query.get('variables')}\n")

    print('-' * 50)

AVAILABLE QUERIES:

--------------------------------------------------

Simple Queries:

 - Database: [MySQL]

   - Query name: top_books
   - Query description: Popularity-based recommendation: find top books with highest number of rating counts
     - Query variables: ['limit']

 - Database: [MongoDB]

   - Query name: top_books
   - Query description: Popularity-based recommendation: find top books with highest number of rating counts
     - Query variables: ['limit']

   - Query name: price_range
   - Query description: Find top M books within price range (Low/High) with good avg rating
     - Query variables: ['low', 'high', 'min_avg', 'limit']

--------------------------------------------------

Complex Queries:

 - Database: [MySQL]

   - Query name: top_recent_books
   - Query description: More complex popularity-based recommendation: find top best rated books with at least S ratings and average rating greater than or equal to A, considering only the N most recent ratings; and providing not only the isbn but also the books' title and authors when joining with books table.
     - Query variables: ['limit', 'min_supt', 'min_avg', 'n_recent']

   - Query name: collaborative_geographic
   - Query description: Recommend books by location+age, falling back to age-only, then global popularity
     - Query variables: ['user_id', 'min_avg', 'proximity_radius', 'limit']

   - Query name: collaborative_geographic_INDEX
   - Query description: Needs Spatial Index: Recommends books by location+age, falling back to age-only, then global popularity
     - Query variables: ['user_id', 'min_avg', 'proximity_radius', 'limit']

   - Query name: genre_collaborative
   - Query description: Recommend books from genres popular among users of same age/gender.
     - Query variables: ['user_id', 'limit', 'min_avg', 'min_supt']

 - Database: [MongoDB]

   - Query name: user_profile_recommendation
   - Query description: Personalized recommendation using user profile (preferences & reading level). Handles comma-separated preference strings.
     - Query variables: ['user_id', 'limit']

--------------------------------------------------

Hybrid Queries:

   - Query name: hybrid_personalized
   - Query description: Hybrid Merge: MySQL (Collab/Geo Haversine) + MongoDB (Content/Profile). Returns merged scores.
     - Query variables: ['user_id', 'min_avg', 'proximity_radius', 'limit']
   - Query outer join, with the keys: {'left': 'isbn', 'right': 'isbn'}
   - Databases for join: {'left': MySQL, 'right': MongoDB}

   - Query name: hybrid_personalized_INDEX
   - Query description: Hybrid Merge: MySQL (Collab/Geo Spatial Index) + MongoDB (Content/Profile). Returns merged scores.
     - Query variables: ['user_id', 'min_avg', 'proximity_radius', 'limit']
   - Query outer join, with the keys: {'left': 'isbn', 'right': 'isbn'}
   - Databases for join: {'left': MySQL, 'right': MongoDB}

--------------------------------------------------

In [149]:
users_to_test = {
# Information gathered from users table
    'has_ratings' : { # boolean column
        True : [],
        False : []
    },
    'has_preferences' : { # boolean column
        True : [],  
        False : []
    },
    'has_valid_location' : [] # has both latitude and longitude defined
}   

def _sample_users_by_bool(col: str, val: bool, limit: int = 5):
    """Return up to `limit` user_id's where `col` equals boolean `val` (MySQL stores booleans as 1/0)."""
    v = 1 if val else 0
    q = text(f"SELECT user_id FROM users WHERE {col} = :v LIMIT :limit")
    with mysql_engine.connect() as conn:
        return [row[0] for row in conn.execute(q, {"v": v, "limit": limit}).fetchall()]

# Sample has_ratings / has_preferences
users_to_test["has_ratings"][True] = _sample_users_by_bool("has_ratings", True, 5)
users_to_test["has_ratings"][False] = _sample_users_by_bool("has_ratings", False, 5)
users_to_test["has_preferences"][True] = _sample_users_by_bool("has_preferences", True, 5)
users_to_test["has_preferences"][False] = _sample_users_by_bool("has_preferences", False, 5)

# Sample users with valid location (both latitude and longitude present)
with mysql_engine.connect() as conn:
    users_to_test["has_valid_location"] = [row[0] for row in conn.execute(text("""
        SELECT user_id FROM users 
        WHERE loc_latitude IS NOT NULL AND loc_longitude IS NOT NULL 
        LIMIT 5"""
    )).fetchall()]

print("Test users sampled successfully.")
print("Users to test:")
for key, val in users_to_test.items():
    print(f" - {key}: {val}")

Test users sampled successfully.
Users to test:
 - has_ratings: {True: [2, 8, 9, 10, 12], False: [1, 3, 4, 5, 6]}
 - has_preferences: {True: [2, 8, 9, 10, 12], False: [1, 3, 4, 5, 6]}
 - has_valid_location: [1, 2, 3, 4, 5]

In [150]:
# Check that all databases aren't empty
print(f"{'DATABASE':<10} | {'TABLE/COLLECTION':<25} | {'COUNT':<10} | {'STATUS':<10}")
print("-" * 65)

# 1. Check MySQL Tables
mysql_tables = ['users', 'books', 'ratings', 'root_genres', 'subgenres', 'book_root_genres', 'book_subgenres']

with mysql_engine.connect() as conn:
    for table in mysql_tables:
        try:
            count = conn.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar()
            count = count if count is not None else 0
            status = "✅ OK" if count > 0 else "⚠️ EMPTY"
            print(f"{'MySQL':<10} | {table:<25} | {count:<10} | {status}")
        except Exception as e:
            print(f"{'MySQL':<10} | {table:<25} | -          | ❌ ERROR")

print("-" * 65)

# 2. Check MongoDB Collections
mongo_colls = ['books_metadata', 'users_profiles']

for coll_name in mongo_colls:
    try:
        count = mongo_db[coll_name].count_documents({})
        status = "✅ OK" if count > 0 else "⚠️ EMPTY"
        print(f"{'MongoDB':<10} | {coll_name:<25} | {count:<10} | {status}")
    except Exception as e:
        print(f"{'MongoDB':<10} | {coll_name:<25} | -          | ❌ ERROR")

DATABASE   | TABLE/COLLECTION          | COUNT      | STATUS
-----------------------------------------------------------------
MySQL      | users                     | 278858     | ✅ OK
MySQL      | books                     | 266457     | ✅ OK
MySQL      | ratings                   | 1016676    | ✅ OK
MySQL      | root_genres               | 28         | ✅ OK
MySQL      | subgenres                 | 99         | ✅ OK
MySQL      | book_root_genres          | 13504      | ✅ OK
MySQL      | book_subgenres            | 13513      | ✅ OK
-----------------------------------------------------------------
MongoDB    | books_metadata            | 266457     | ✅ OK
MongoDB    | users_profiles            | 278858     | ✅ OK

In [151]:
# DEBUGGING CELL: Test individual queries manually

print("--- DEBUGGING INDIVIDUAL QUERIES ---")

# 1. Test MySQL Connection & Simple Query directly
print("\n1. Testing MySQL Direct Query...")
with mysql_engine.connect() as conn:
    # Simple count to verify connectivity
    cnt = conn.execute(text("SELECT COUNT(*) FROM ratings")).scalar()
    print(f"   Ratings count: {cnt}")
    
    # Run the actual top_books SQL manually
    sql = """
        SELECT isbn, COUNT(*) AS rating_count
        FROM ratings
        GROUP BY isbn
        ORDER BY rating_count DESC
        LIMIT 5;
    """
    try:
        res = conn.execute(text(sql)).fetchall()
        print(f"   Manual SQL Result: {res}")
    except Exception as e:
        print(f"   Manual SQL Error: {e}")

# 2. Test MongoDB Direct Query
print("\n2. Testing MongoDB Direct Query...")
try:
    pipeline = [
        { "$sort": { "rating_metrics.rating_count": -1 } },
        { "$limit": 5 },
        { "$project": { "isbn": "$_id", "rating_count": "$rating_metrics.rating_count", "_id": 0 }}
    ]
    res = list(mongo_db['books_metadata'].aggregate(pipeline))
    print(f"   Manual Mongo Result: {res}")
except Exception as e:
    print(f"   Manual Mongo Error: {e}")

# 3. Test via execute_query helper
print("\n3. Testing via execute_query() helper...")
raw_conn = mysql_engine.raw_connection()
cursor = raw_conn.cursor(dictionary=True)

try:
    # Test MySQL top_books
    res_mysql = execute_query(
        category='Simple', 
        db_type='MySQL', 
        query_name='top_books', 
        params={'limit': 5}, 
        sql_cursor=cursor, 
        mongo_db=mongo_db
    )
    print(f"   Helper MySQL Result Rows: {len(res_mysql.get('data', []))}")
    display(res_mysql['data'])

    # Test MongoDB top_books
    res_mongo = execute_query(
        category='Simple', 
        db_type='MongoDB', 
        query_name='top_books', 
        params={'limit': 5}, 
        sql_cursor=cursor, 
        mongo_db=mongo_db
    )
    print(f"   Helper MongoDB Result Rows: {len(res_mongo.get('data', []))}")
    display(res_mongo['data'])

finally:
    cursor.close()
    raw_conn.close()

--- DEBUGGING INDIVIDUAL QUERIES ---

1. Testing MySQL Direct Query...
   Ratings count: 1016676
   Manual SQL Result: [('0971880107', 2502), ('0316666343', 1295), ('0385504209', 883), ('0060928336', 732), ('0312195516', 723)]

2. Testing MongoDB Direct Query...
   Manual Mongo Result: [{'isbn': '0374157065'}, {'isbn': '0393045218'}, {'isbn': '0002005018'}, {'isbn': '0195153448'}, {'isbn': '0060973129'}]

3. Testing via execute_query() helper...
--- EXECUTION: top_books (MySQL) ---
   Helper MySQL Result Rows: 5

         isbn  rating_count
0  0971880107          2502
1  0316666343          1295
2  0385504209           883
3  0060928336           732
4  0312195516           723

--- EXECUTION: top_books (MongoDB) ---
   Helper MongoDB Result Rows: 5

         isbn  rating_count
0  0971880107          2502
1  0316666343          1295
2  0385504209           883
3  0060928336           732
4  0312195516           723

In [154]:
import pandas as pd
from IPython.display import display

# ==========================================
# 1. SETUP & PARAMETERS
# ==========================================
test_params = {
    'limit': 7,
    'min_avg': 6,
    'min_supt': 3,
    'n_recent': 200,
    'low': 5,
    'high': 150,
    'proximity_radius': 4000,
    'user_id': None 
}

# Storage for the two sections of your report
performance_metrics = [] # Will hold: [Query Name, DB Type, Time, Rows, Status]
execution_details = []   # Will hold: [Query Name, Params, Result Head, Explain Plan]

def get_best_user_for_query(query_name):
    """(Helper function remains the same)"""
    # Geographic/Hybrid queries need valid location data
    if 'geographic' in query_name or 'hybrid' in query_name:
        if users_to_test['has_valid_location']:
            return users_to_test['has_valid_location'][0]
    # Profile/Content queries need preferences
    if 'profile' in query_name or 'content' in query_name:
        if users_to_test['has_preferences'][True]:
            return users_to_test['has_preferences'][True][0]
    # Default fallback
    if users_to_test['has_ratings'][True]:
        return users_to_test['has_ratings'][True][0]
    return 1

# ==========================================
# 2. EXECUTION PHASE (Collect Data)
# ==========================================
raw_conn = mysql_engine.raw_connection()

try:
    cursor = raw_conn.cursor(dictionary=True)
    print("🚀 Starting Batch Execution...\n")

    # Helper to process a single query entry
    def process_query(category, db_type, query_name):
        # 1. Prepare Parameters
        current_params = test_params.copy()
        current_params['user_id'] = get_best_user_for_query(query_name)
        
        # Filter params to show only those used by the query
        if category == 'Hybrid':
            q_def = QUERIES[category][query_name]
        else:
            q_def = QUERIES[category][db_type][query_name]
            
        needed_vars = q_def.get('variables', [])
        filtered_params = {k: current_params[k] for k in needed_vars if k in current_params}

        # 2. Run Execution (Timing & Data)
        try:
            res_exec = execute_query(
                category=category, db_type=db_type, query_name=query_name,
                params=current_params, sql_cursor=cursor, mongo_db=mongo_db,
                mode='execution'
            )
            
            # Handle Errors Gracefully
            if 'error' in res_exec:
                performance_metrics.append({
                    "Category": category, "DB": db_type, "Query": query_name,
                    "Status": "❌ Failed", "Time (s)": 0, "Rows": 0, "Error": res_exec['error']
                })
                return

            # Success - Store Metrics
            duration = res_exec.get('duration_seconds', 0)
            df = res_exec.get('data')
            rows = len(df) if df is not None else 0
            
            performance_metrics.append({
                "Category": category, "DB": db_type, "Query": query_name,
                "Status": "✅ Success", "Time (s)": round(duration, 4), "Rows": rows
            })

            # 3. Run Explain (Analysis)
            res_explain = execute_query(
                category=category, db_type=db_type, query_name=query_name,
                params=current_params, sql_cursor=cursor, mongo_db=mongo_db,
                mode='explain'
            )
            
            # 4. Store Details for later display
            # Note: We store only df.head() to save memory
            execution_details.append({
                "meta": f"{category} | {db_type} | {query_name}",
                "params": filtered_params,
                "data": df if df is not None and not df.empty else None,
                "explain_plan": res_explain.get('explain_plan')
            })

        except Exception as e:
            performance_metrics.append({
                "Category": category, "DB": db_type, "Query": query_name,
                "Status": "❌ Crash", "Time (s)": 0, "Rows": 0, "Error": str(e)
            })

    # --- Main Loop ---
    for category, content in QUERIES.items():
        # Handle Hybrid (Flattened)
        if category == 'Hybrid':
            for q_name in content.keys():
                if not q_name.endswith('_INDEX'):
                    process_query(category, 'Combined', q_name)
        # Handle Standard (Nested)
        else:
            for db_type, queries in content.items():
                for q_name in queries.keys():
                    if not q_name.endswith('_INDEX'):
                        process_query(category, db_type, q_name)

finally:
    cursor.close()
    raw_conn.close()
    print("🏁 Execution Complete. Generating Reports...")

# ==========================================
# 3. REPORTING PHASE
# ==========================================

# --- SECTION 1: PERFORMANCE SUMMARY DATAFRAME ---
print("\n" + "="*80)
print("📊 SECTION 1: PERFORMANCE SUMMARY")
print("="*80)
df_results = pd.DataFrame(performance_metrics)
# Reorder columns for readability
cols = ["Category", "DB", "Query", "Status", "Time (s)", "Rows"]
if "Error" in df_results.columns: cols.append("Error")
display(df_results[cols])


# --- SECTION 2: DETAILED BREAKDOWN ---
print("\n\n" + "="*80)
print("🔍 SECTION 2: DETAILED QUERY LOGS (Sample + Plans)")
print("="*80)

for log in execution_details:
    print(f"\n🔹 {log['meta']}")
    print(f"   Params: {log['params']}")
    print("-" * 50)
    
    # 1. Data Sample
    print("📋 Result:")
    if log['data'] is not None:
        display(log['data'])
    else:
        print("   (No data returned)")

    # 2. Explain Plan
    print("\n🧠 Explain Plan:")
    plan = log['explain_plan']

    if plan is not None:
        if isinstance(plan, dict):
            # For Hybrid or Mongo multi-collection
            for k, v in plan.items():
                print(f"[{k}]:")
                if hasattr(v, 'head'): # It's a dataframe
                    display(v)
                else:
                    # Try to display dicts nicely, fallback to print
                    try:
                        display(v)
                    except:
                        print(v)
        elif hasattr(plan, 'head'):
            display(plan)
        else:
            print(plan)
    else:
        print("No explain plan available.")
                
    print("_" * 80)

🚀 Starting Batch Execution...

--- EXECUTION: top_books (MySQL) ---
--- EXPLAIN: top_books (MySQL) ---
--- EXECUTION: top_books (MongoDB) ---
--- EXPLAIN: top_books (MongoDB) ---
--- EXECUTION: price_range (MongoDB) ---
--- EXPLAIN: price_range (MongoDB) ---
--- EXECUTION: top_recent_books (MySQL) ---
--- EXPLAIN: top_recent_books (MySQL) ---
--- EXECUTION: collaborative_geographic (MySQL) ---
--- EXPLAIN: collaborative_geographic (MySQL) ---
--- EXECUTION: genre_collaborative (MySQL) ---
--- EXPLAIN: genre_collaborative (MySQL) ---
--- EXECUTION: user_profile_recommendation (MongoDB) ---
--- EXPLAIN: user_profile_recommendation (MongoDB) ---
--- EXECUTION: hybrid_personalized (Combined) ---
--- EXPLAIN: hybrid_personalized (Combined) ---
🏁 Execution Complete. Generating Reports...

================================================================================
📊 SECTION 1: PERFORMANCE SUMMARY
================================================================================

  Category        DB                        Query     Status  Time (s)  Rows
0   Simple     MySQL                    top_books  ✅ Success    0.3130     7
1   Simple   MongoDB                    top_books  ✅ Success    0.3144     7
2   Simple   MongoDB                  price_range  ✅ Success    0.2296     7
3  Complex     MySQL             top_recent_books  ✅ Success    1.6532     7
4  Complex     MySQL     collaborative_geographic  ✅ Success    5.2681     7
5  Complex     MySQL          genre_collaborative  ✅ Success    1.7879     7
6  Complex   MongoDB  user_profile_recommendation  ✅ Success    0.5325     7
7   Hybrid  Combined          hybrid_personalized  ✅ Success    6.8832     7

================================================================================
🔍 SECTION 2: DETAILED QUERY LOGS (Sample + Plans)
================================================================================

🔹 Simple | MySQL | top_books
   Params: {'limit': 7}
--------------------------------------------------
📋 Result:

         isbn  rating_count
0  0971880107          2502
1  0316666343          1295
2  0385504209           883
3  0060928336           732
4  0312195516           723
5  044023722X           647
6  0142001740           615

🧠 Explain Plan:

,id,select_type,table,type,possible_keys,key,key_len,ref,rows,Extra
0,1,SIMPLE,ratings,index,None,isbn,42,None,1003348,Using index; Using temporary; Using filesort

________________________________________________________________________________

🔹 Simple | MongoDB | top_books
   Params: {'limit': 7}
--------------------------------------------------
📋 Result:

         isbn  rating_count
0  0971880107          2502
1  0316666343          1295
2  0385504209           883
3  0060928336           732
4  0312195516           723
5  044023722X           647
6  0142001740           615

🧠 Explain Plan:
[books_metadata]:

{'explainVersion': '1',
 'stages': [{'$cursor': {'queryPlanner': {'namespace': '68e39feadeb4b70ed33f9ebc_bookrec.books_metadata',
     'parsedQuery': {},
     'indexFilterSet': False,
     'queryHash': '28299F05',
     'planCacheShapeHash': '28299F05',
     'planCacheKey': 'A3DBFDA1',
     'optimizationTimeMillis': 0,
     'maxIndexedOrSolutionsReached': False,
     'maxIndexedAndSolutionsReached': False,
     'maxScansToExplodeReached': False,
     'prunedSimilarIndexes': False,
     'winningPlan': {'isCached': False,
      'stage': 'PROJECTION_DEFAULT',
      'transformBy': {'_id': 1, 'rating_metrics.r_total': 1},
      'inputStage': {'stage': 'SORT',
       'sortPattern': {'rating_metrics.r_total': -1},
       'memLimit': 33554432,
       'limitAmount': 7,
       'type': 'simple',
       'inputStage': {'stage': 'COLLSCAN', 'direction': 'forward'}}},
     'rejectedPlans': []}}},
  {'$project': {'isbn': '$_id',
    'rating_count': '$rating_metrics.r_total',
    '_id': False}}],
 'queryShapeHash': 'A4CCF2625ABFA7533E1984A9B1D17F2655344150CB0A9A3767A96E83B51C758B',
 'serverInfo': {'host': 'atlas-viol3m-shard-00-01.7rpsn.mongodb.net',
  'port': 27000,
  'version': '8.0.16',
  'gitVersion': 'ba70b6a13fda907977110bf46e6c8137f5de48f6'},
 'serverParameters': {'internalQueryFacetBufferSizeBytes': 104857600,
  'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
  'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
  'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
  'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
  'internalQueryProhibitBlockingMergeOnMongoS': 0,
  'internalQueryMaxAddToSetBytes': 104857600,
  'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
  'internalQueryFrameworkControl': 'trySbeRestricted',
  'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1},
 'command': {'aggregate': 'books_metadata',
  'pipeline': [{'$sort': {'rating_metrics.r_total': -1}},
   {'$limit': 7},
   {'$project': {'isbn': '$_id',
     'rating_count': '$rating_metrics.r_total',
     '_id': 0}}],
  'explain': True,
  'apiVersion': '1',
  'lsid': {'id': Binary(b'\xd33\xa3y=\xb0@5\x89hW\xcb\xe2\x9ct\x9f', 4)},
  '$clusterTime': {'clusterTime': Timestamp(1765205676, 1),
   'signature': {'hash': b'\xea+\xcf\xfe\x9b\xfeL\xd1\x05\x94iw\x9b\xaa\x87\x1d4s-\xed',
    'keyId': 7542901657785335835}},
  '$db': '68e39feadeb4b70ed33f9ebc_bookrec',
  'maxTimeMS': 300000,
  'comment': {'AtlasProxyDBPrefix': '68e39feadeb4b70ed33f9ebc_',
   'AtlasProxyAppName': 'Cluster0',
   'AtlasProxyClientMetadata': {'driver': {'name': 'PyMongo|c',
     'version': '4.15.3'},
    'os': {'type': 'Linux',
     'name': 'Linux',
     'architecture': 'x86_64',
     'version': '6.17.4-arch2-1'},
    'platform': 'CPython 3.13.7.final.0',
    'application': {'name': 'Cluster0'},
    'clientTLSVersion': 'TLS 1.3'}}},
 'ok': 1.0,
 '$clusterTime': {'clusterTime': Timestamp(1765205676, 2),
  'signature': {'hash': b'\xea+\xcf\xfe\x9b\xfeL\xd1\x05\x94iw\x9b\xaa\x87\x1d4s-\xed',
   'keyId': 7542901657785335835}},
 'operationTime': Timestamp(1765205676, 2)}

________________________________________________________________________________

🔹 Simple | MongoDB | price_range
   Params: {'low': 5, 'high': 150, 'min_avg': 6, 'limit': 7}
--------------------------------------------------
📋 Result:

         isbn  price_usd  r_avg  rating_score
0  1571456988      14.00   10.0      0.859062
1  0060256672      10.32    9.4      0.849128
2  0312992416       7.99    9.8      0.843138
3  0671027441      25.14   10.0      0.827858
4  1932560491      24.87   10.0      0.827858
5  037581177X      26.14   10.0      0.827858
6  0553380400      11.90   10.0      0.827858

🧠 Explain Plan:
[books_metadata]:

{'explainVersion': '1',
 'stages': [{'$cursor': {'queryPlanner': {'namespace': '68e39feadeb4b70ed33f9ebc_bookrec.books_metadata',
     'parsedQuery': {'$and': [{'extra_metadata.price_usd': {'$lte': 150}},
       {'extra_metadata.price_usd': {'$gte': 5}},
       {'rating_metrics.r_avg': {'$gte': 6}}]},
     'indexFilterSet': False,
     'queryHash': '987D7AD4',
     'planCacheShapeHash': '987D7AD4',
     'planCacheKey': 'BE34BE1C',
     'optimizationTimeMillis': 0,
     'maxIndexedOrSolutionsReached': False,
     'maxIndexedAndSolutionsReached': False,
     'maxScansToExplodeReached': False,
     'prunedSimilarIndexes': False,
     'winningPlan': {'isCached': False,
      'stage': 'PROJECTION_DEFAULT',
      'transformBy': {'_id': 1,
       'extra_metadata.price_usd': 1,
       'rating_metrics.r_avg': 1,
       'rating_metrics.rating_score': 1},
      'inputStage': {'stage': 'SORT',
       'sortPattern': {'rating_metrics.rating_score': -1},
       'memLimit': 33554432,
       'limitAmount': 7,
       'type': 'simple',
       'inputStage': {'stage': 'COLLSCAN',
        'filter': {'$and': [{'extra_metadata.price_usd': {'$lte': 150}},
          {'extra_metadata.price_usd': {'$gte': 5}},
          {'rating_metrics.r_avg': {'$gte': 6}}]},
        'direction': 'forward'}}},
     'rejectedPlans': []}}},
  {'$project': {'isbn': '$_id',
    'price_usd': '$extra_metadata.price_usd',
    'r_avg': '$rating_metrics.r_avg',
    'rating_score': '$rating_metrics.rating_score',
    '_id': False}}],
 'queryShapeHash': 'E726E8AF12C623FECE3F3CC418AEDC512FDB0E5E5770B0273AC44C680038C8E7',
 'serverInfo': {'host': 'atlas-viol3m-shard-00-01.7rpsn.mongodb.net',
  'port': 27000,
  'version': '8.0.16',
  'gitVersion': 'ba70b6a13fda907977110bf46e6c8137f5de48f6'},
 'serverParameters': {'internalQueryFacetBufferSizeBytes': 104857600,
  'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
  'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
  'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
  'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
  'internalQueryProhibitBlockingMergeOnMongoS': 0,
  'internalQueryMaxAddToSetBytes': 104857600,
  'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
  'internalQueryFrameworkControl': 'trySbeRestricted',
  'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1},
 'command': {'aggregate': 'books_metadata',
  'pipeline': [{'$match': {'extra_metadata.price_usd': {'$gte': 5,
      '$lte': 150},
     'rating_metrics.r_avg': {'$gte': 6}}},
   {'$sort': {'rating_metrics.rating_score': -1}},
   {'$limit': 7},
   {'$project': {'isbn': '$_id',
     'price_usd': '$extra_metadata.price_usd',
     'r_avg': '$rating_metrics.r_avg',
     'rating_score': '$rating_metrics.rating_score',
     '_id': 0}}],
  'explain': True,
  'apiVersion': '1',
  'lsid': {'id': Binary(b'\xd33\xa3y=\xb0@5\x89hW\xcb\xe2\x9ct\x9f', 4)},
  '$clusterTime': {'clusterTime': Timestamp(1765205676, 2),
   'signature': {'hash': b'\xea+\xcf\xfe\x9b\xfeL\xd1\x05\x94iw\x9b\xaa\x87\x1d4s-\xed',
    'keyId': 7542901657785335835}},
  '$db': '68e39feadeb4b70ed33f9ebc_bookrec',
  'maxTimeMS': 300000,
  'comment': {'AtlasProxyDBPrefix': '68e39feadeb4b70ed33f9ebc_',
   'AtlasProxyAppName': 'Cluster0',
   'AtlasProxyClientMetadata': {'driver': {'name': 'PyMongo|c',
     'version': '4.15.3'},
    'os': {'type': 'Linux',
     'name': 'Linux',
     'architecture': 'x86_64',
     'version': '6.17.4-arch2-1'},
    'platform': 'CPython 3.13.7.final.0',
    'application': {'name': 'Cluster0'},
    'clientTLSVersion': 'TLS 1.3'}}},
 'ok': 1.0,
 '$clusterTime': {'clusterTime': Timestamp(1765205676, 2),
  'signature': {'hash': b'\xea+\xcf\xfe\x9b\xfeL\xd1\x05\x94iw\x9b\xaa\x87\x1d4s-\xed',
   'keyId': 7542901657785335835}},
 'operationTime': Timestamp(1765205676, 2)}

________________________________________________________________________________

🔹 Complex | MySQL | top_recent_books
   Params: {'limit': 7, 'min_supt': 3, 'min_avg': 6, 'n_recent': 200}
--------------------------------------------------
📋 Result:

,isbn,title,authors,rating_count,avg_rating
0,1888054557,Postmarked Yesteryear: 30 Rare Holiday Postcards,['Pamela E. Apkarian-Russell'],11,10.0000
1,0394800893,The Sneetches and Other Stories,['Dr. Seuss'],8,10.0000
2,1571456988,Uncle John's Supremely Satisfying Bathroom Rea...,"['Bathroom Readers Institute', ""Bathroom Reade...",7,10.0000
3,089471838X,Natural California: A Postcard Book,['Not Applicable (Na )'],7,10.0000
4,0395282659,The Hobbit,['J. R. R. Tolkien'],6,10.0000
5,0395193958,The Lord of the Rings (Leatherette Collector's...,['J. R. R. Tolkien'],6,10.0000
6,0679821481,Six by Seuss: A Treasury of Dr. Seuss Classics,['Seuss'],6,10.0000

🧠 Explain Plan:

,id,select_type,table,type,possible_keys,key,key_len,ref,rows,Extra
0,1,PRIMARY,<derived4>,ALL,None,None,None,None,1003348,Using where; Using filesort
1,1,PRIMARY,b,eq_ref,PRIMARY,PRIMARY,42,bs.isbn,1,
2,4,DERIVED,<derived2>,ALL,None,None,None,None,1003348,Using where; Using temporary; Using filesort
3,2,DERIVED,r,ALL,None,None,None,None,1003348,Using where; Using temporary

________________________________________________________________________________

🔹 Complex | MySQL | collaborative_geographic
   Params: {'user_id': 1, 'min_avg': 6, 'proximity_radius': 4000, 'limit': 7}
--------------------------------------------------
📋 Result:

,isbn,title,authors,rating_count,avg_rating
0,0060256656,The Giving Tree,['Shel Silverstein'],8,10.0000
1,0439425220,Harry Potter and the Chamber of Secrets Postca...,['J. K. Rowling'],7,10.0000
2,0517693119,More Than Complete Hitchhiker's Guide,['Douglas Adams'],7,10.0000
3,0441068804,The Blue Sword,['Robin McKinley'],6,10.0000
4,0394800796,How the Grinch Stole Christmas!,['Dr. Seuss'],5,10.0000
5,0394831292,"Oh, the Thinks You Can Think! (I Can Read It A...",['Dr. Seuss'],5,10.0000
6,0440224837,The Long Road Home,['Danielle Steel'],5,10.0000

🧠 Explain Plan:

,id,select_type,table,type,possible_keys,key,key_len,ref,rows,Extra
0,1,PRIMARY,<derived5>,ALL,None,None,None,None,265512,Using filesort
1,5,DERIVED,users,const,PRIMARY,PRIMARY,4,const,1,Using temporary; Using filesort
2,5,DERIVED,b,ALL,PRIMARY,None,None,None,265512,
3,5,DERIVED,r,ref,"PRIMARY,isbn",isbn,42,bookrec.b.isbn,3,Using index condition; Using where
4,5,DERIVED,u,eq_ref,PRIMARY,PRIMARY,4,bookrec.r.user_id,1,Using where
5,7,UNION,None,None,None,None,None,None,None,Impossible WHERE
6,9,SUBQUERY,users,const,PRIMARY,PRIMARY,4,const,1,
7,9,SUBQUERY,u,ALL,PRIMARY,None,None,None,276061,Using where
8,4,DERIVED,users,const,PRIMARY,PRIMARY,4,const,1,
9,4,DERIVED,u,ALL,PRIMARY,None,None,None,276061,Using where
10,10,UNION,None,None,None,None,None,None,None,Impossible WHERE
11,12,SUBQUERY,<derived18>,ALL,None,None,None,None,100,
12,18,DERIVED,users,const,PRIMARY,PRIMARY,4,const,1,
13,18,DERIVED,u,ALL,PRIMARY,None,None,None,276061,Using where
14,11,SUBQUERY,users,const,PRIMARY,PRIMARY,4,const,1,
15,11,SUBQUERY,u,ALL,PRIMARY,None,None,None,276061,Using where

________________________________________________________________________________

🔹 Complex | MySQL | genre_collaborative
   Params: {'user_id': 2, 'limit': 7, 'min_avg': 6, 'min_supt': 3}
--------------------------------------------------
📋 Result:

,isbn,title,authors,rating_count,avg_rating
0,0060256710,The Missing Piece (Ursula Nordstrom Book),['Shel Silverstein'],3,10.0000
1,0449909298,Born for Love: Reflections on Loving,['Leo F. Buscaglia'],3,10.0000
2,075966661X,Exit Unicorns,['Cindy Brandner'],3,10.0000
3,1932560491,Bedtime Stories for Women,['Nancy Madore'],3,10.0000
4,0312992416,Kiss of the Night (A Dark-Hunter Novel),['Sherrilyn Kenyon'],10,9.8000
5,0767903315,Letters of a Nation: A Collection of Extraordi...,['Andrew Carroll'],4,9.7500
6,0060199385,The One That Got Away: An Emma Price Mystery (...,"['Naomi R. Rand', 'Naomi Rand']",3,9.6667

🧠 Explain Plan:

,id,select_type,table,type,possible_keys,key,key_len,ref,rows,Extra
0,1,PRIMARY,<derived6>,ALL,None,None,None,None,5370,Using filesort
1,6,DERIVED,<derived4>,ALL,None,None,None,None,5,Start temporary; Using temporary; Using filesort
2,6,DERIVED,brg,ref,"PRIMARY,root_id",root_id,4,top_genres.root_id,358,Using index; End temporary
3,6,DERIVED,b,eq_ref,PRIMARY,PRIMARY,42,bookrec.brg.isbn,1,Using where
4,6,DERIVED,r,ref,isbn,isbn,42,bookrec.brg.isbn,3,Using where
5,8,MATERIALIZED,ratings,ref,"PRIMARY,isbn",PRIMARY,4,const,1,
6,4,DERIVED,users,const,PRIMARY,PRIMARY,4,const,1,Using temporary; Using filesort
7,4,DERIVED,brg,index,"PRIMARY,root_id",root_id,4,None,10046,Using index
8,4,DERIVED,r,ref,"PRIMARY,isbn",isbn,42,bookrec.brg.isbn,3,Using index condition; Using where
9,4,DERIVED,u,eq_ref,PRIMARY,PRIMARY,4,bookrec.r.user_id,1,Using where

________________________________________________________________________________

🔹 Complex | MongoDB | user_profile_recommendation
   Params: {'user_id': 2, 'limit': 7}
--------------------------------------------------
📋 Result:

         isbn     score  price                  genres  rating_avg
0  068484477X  1.431801  10.88             ['Fiction']    8.056000
1  0786867647  1.352094  16.75  ['Biography & Memoir']    8.230769
2  0679731148  1.318520  10.17  ['Biography & Memoir']    8.000000
3  0440226104  1.302203  25.01             ['Fiction']    7.500000
4  0553578685  1.233824   7.99             ['Fiction']    7.961538
5  0515136379  1.233444   7.99             ['Fiction']    7.940000
6  0451190491  1.230813  25.97             ['Fiction']    8.473684

🧠 Explain Plan:
[users_profiles]:

{'explainVersion': '1',
 'stages': [{'$cursor': {'queryPlanner': {'namespace': '68e39feadeb4b70ed33f9ebc_bookrec.users_profiles',
     'parsedQuery': {'_id': {'$eq': 2}},
     'indexFilterSet': False,
     'queryHash': '29E43E3B',
     'planCacheShapeHash': '29E43E3B',
     'planCacheKey': '1D3B2C31',
     'optimizationTimeMillis': 0,
     'maxIndexedOrSolutionsReached': False,
     'maxIndexedAndSolutionsReached': False,
     'maxScansToExplodeReached': False,
     'prunedSimilarIndexes': False,
     'winningPlan': {'isCached': False,
      'stage': 'PROJECTION_DEFAULT',
      'transformBy': {'preferences': 1, 'profile.mean_rating': 1, '_id': 0},
      'inputStage': {'stage': 'IDHACK'}},
     'rejectedPlans': []}}},
  {'$addFields': {'preferences': {'pref_root_genres_arr': {'$split': [{'$ifNull': ['$preferences.pref_root_genres',
         {'$const': ''}]},
       {'$const': ','}]},
     'pref_subgenres_arr': {'$split': [{'$ifNull': ['$preferences.pref_subgenres',
         {'$const': ''}]},
       {'$const': ','}]},
     'pref_authors_arr': {'$split': [{'$ifNull': ['$preferences.pref_authors',
         {'$const': ''}]},
       {'$const': ','}]},
     'pref_publishers_arr': {'$split': [{'$ifNull': ['$preferences.pref_publisher',
         {'$const': ''}]},
       {'$const': ','}]},
     'pref_years_arr': {'$split': [{'$ifNull': ['$preferences.pref_pub_year',
         {'$const': ''}]},
       {'$const': ','}]}}}},
  {'$lookup': {'from': 'books_metadata',
    'as': 'recs',
    'let': {'p_root': '$preferences.pref_root_genres_arr',
     'p_sub': '$preferences.pref_subgenres_arr',
     'p_authors': '$preferences.pref_authors_arr',
     'p_publishers': '$preferences.pref_publishers_arr',
     'p_years': '$preferences.pref_years_arr',
     'p_min': {'$ifNull': ['$preferences.pref_price_min', {'$const': 0}]},
     'p_max': {'$ifNull': ['$preferences.pref_price_max', {'$const': 1000}]},
     'p_avg_rating': {'$ifNull': ['$profile.mean_rating', {'$const': 0}]}},
    'pipeline': [{'$match': {'$expr': {'$and': [{'$or': [{'$eq': [{'$size': '$$p_root'},
             0]},
           {'$eq': [{'$arrayElemAt': ['$$p_root', 0]}, '']},
           {'$cond': [{'$isArray': '$extra_metadata.root_genres'},
             {'$gt': [{'$size': {'$setIntersection': ['$extra_metadata.root_genres',
                  '$$p_root']}},
               0]},
             {'$in': ['$extra_metadata.root_genres', '$$p_root']}]}]},
         {'$or': [{'$eq': ['$extra_metadata.price_usd', None]},
           {'$and': [{'$gte': ['$extra_metadata.price_usd', '$$p_min']},
             {'$lte': ['$extra_metadata.price_usd', '$$p_max']}]}]},
         {'$gte': ['$rating_metrics.r_avg', '$$p_avg_rating']}]}}},
     {'$addFields': {'personal_score': {'$add': [{'$ifNull': ['$rating_metrics.rating_score',
           0]},
         {'$cond': [{'$cond': [{'$isArray': '$extra_metadata.subgenres'},
             {'$gt': [{'$size': {'$setIntersection': ['$extra_metadata.subgenres',
                  '$$p_sub']}},
               0]},
             {'$in': ['$extra_metadata.subgenres', '$$p_sub']}]},
           2.0,
           0.0]},
         {'$cond': [{'$in': ['$extra_metadata.author', '$$p_authors']},
           3.0,
           0.0]},
         {'$cond': [{'$in': ['$extra_metadata.publisher', '$$p_publishers']},
           1.0,
           0.0]},
         {'$cond': [{'$in': [{'$toString': '$extra_metadata.publication_year'},
             '$$p_years']},
           1.0,
           0.0]},
         {'$ifNull': ['$popularity_metrics.popularity', 0]}]}}},
     {'$sort': {'personal_score': -1}},
     {'$limit': 7}],
    'unwinding': {'preserveNullAndEmptyArrays': False}}},
  {'$project': {'isbn': '$recs._id',
    'score': '$recs.personal_score',
    'title': '$recs.title',
    'price': '$recs.extra_metadata.price_usd',
    'genres': '$recs.extra_metadata.root_genres',
    'rating_avg': '$recs.rating_metrics.r_avg',
    '_id': False}}],
 'queryShapeHash': 'F43D419E8C2ABF8C2C19A55B12D16EEBD3C55CFD45EA21C922A00B178C8839DE',
 'serverInfo': {'host': 'atlas-viol3m-shard-00-01.7rpsn.mongodb.net',
  'port': 27000,
  'version': '8.0.16',
  'gitVersion': 'ba70b6a13fda907977110bf46e6c8137f5de48f6'},
 'serverParameters': {'internalQueryFacetBufferSizeBytes': 104857600,
  'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
  'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
  'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
  'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
  'internalQueryProhibitBlockingMergeOnMongoS': 0,
  'internalQueryMaxAddToSetBytes': 104857600,
  'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
  'internalQueryFrameworkControl': 'trySbeRestricted',
  'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1},
 'command': {'aggregate': 'users_profiles',
  'pipeline': [{'$match': {'_id': 2}},
   {'$addFields': {'preferences.pref_root_genres_arr': {'$split': [{'$ifNull': ['$preferences.pref_root_genres',
         '']},
       ',']},
     'preferences.pref_subgenres_arr': {'$split': [{'$ifNull': ['$preferences.pref_subgenres',
         '']},
       ',']},
     'preferences.pref_authors_arr': {'$split': [{'$ifNull': ['$preferences.pref_authors',
         '']},
       ',']},
     'preferences.pref_publishers_arr': {'$split': [{'$ifNull': ['$preferences.pref_publisher',
         '']},
       ',']},
     'preferences.pref_years_arr': {'$split': [{'$ifNull': ['$preferences.pref_pub_year',
         '']},
       ',']}}},
   {'$lookup': {'from': 'books_metadata',
     'let': {'p_root': '$preferences.pref_root_genres_arr',
      'p_sub': '$preferences.pref_subgenres_arr',
      'p_authors': '$preferences.pref_authors_arr',
      'p_publishers': '$preferences.pref_publishers_arr',
      'p_years': '$preferences.pref_years_arr',
      'p_min': {'$ifNull': ['$preferences.pref_price_min', 0]},
      'p_max': {'$ifNull': ['$preferences.pref_price_max', 1000]},
      'p_avg_rating': {'$ifNull': ['$profile.mean_rating', 0]}},
     'pipeline': [{'$match': {'$expr': {'$and': [{'$or': [{'$eq': [{'$size': '$$p_root'},
              0]},
            {'$eq': [{'$arrayElemAt': ['$$p_root', 0]}, '']},
            {'$cond': [{'$isArray': '$extra_metadata.root_genres'},
              {'$gt': [{'$size': {'$setIntersection': ['$extra_metadata.root_genres',
                   '$$p_root']}},
                0]},
              {'$in': ['$extra_metadata.root_genres', '$$p_root']}]}]},
          {'$or': [{'$eq': ['$extra_metadata.price_usd', None]},
            {'$and': [{'$gte': ['$extra_metadata.price_usd', '$$p_min']},
              {'$lte': ['$extra_metadata.price_usd', '$$p_max']}]}]},
          {'$gte': ['$rating_metrics.r_avg', '$$p_avg_rating']}]}}},
      {'$addFields': {'personal_score': {'$add': [{'$ifNull': ['$rating_metrics.rating_score',
            0]},
          {'$cond': [{'$cond': [{'$isArray': '$extra_metadata.subgenres'},
              {'$gt': [{'$size': {'$setIntersection': ['$extra_metadata.subgenres',
                   '$$p_sub']}},
                0]},
              {'$in': ['$extra_metadata.subgenres', '$$p_sub']}]},
            2.0,
            0.0]},
          {'$cond': [{'$in': ['$extra_metadata.author', '$$p_authors']},
            3.0,
            0.0]},
          {'$cond': [{'$in': ['$extra_metadata.publisher', '$$p_publishers']},
            1.0,
            0.0]},
          {'$cond': [{'$in': [{'$toString': '$extra_metadata.publication_year'},
              '$$p_years']},
            1.0,
            0.0]},
          {'$ifNull': ['$popularity_metrics.popularity', 0]}]}}},
      {'$sort': {'personal_score': -1}},
      {'$limit': 7}],
     'as': 'recs'}},
   {'$unwind': '$recs'},
   {'$project': {'isbn': '$recs._id',
     'score': '$recs.personal_score',
     'title': '$recs.title',
     'price': '$recs.extra_metadata.price_usd',
     'genres': '$recs.extra_metadata.root_genres',
     'rating_avg': '$recs.rating_metrics.r_avg',
     '_id': 0}}],
  'explain': True,
  'apiVersion': '1',
  'lsid': {'id': Binary(b'\xd33\xa3y=\xb0@5\x89hW\xcb\xe2\x9ct\x9f', 4)},
  '$clusterTime': {'clusterTime': Timestamp(1765205686, 1),
   'signature': {'hash': b"\xfd'f\xf9\xb9\x90\xbfWXI\xa4\xc4e\xf0\x10\x82\xbb\xa3\x8f\x8d",
    'keyId': 7542901657785335835}},
  '$db': '68e39feadeb4b70ed33f9ebc_bookrec',
  'maxTimeMS': 300000,
  'comment': {'AtlasProxyDBPrefix': '68e39feadeb4b70ed33f9ebc_',
   'AtlasProxyAppName': 'Cluster0',
   'AtlasProxyClientMetadata': {'driver': {'name': 'PyMongo|c',
     'version': '4.15.3'},
    'os': {'type': 'Linux',
     'name': 'Linux',
     'architecture': 'x86_64',
     'version': '6.17.4-arch2-1'},
    'platform': 'CPython 3.13.7.final.0',
    'application': {'name': 'Cluster0'},
    'clientTLSVersion': 'TLS 1.3'}}},
 'ok': 1.0,
 '$clusterTime': {'clusterTime': Timestamp(1765205686, 1),
  'signature': {'hash': b"\xfd'f\xf9\xb9\x90\xbfWXI\xa4\xc4e\xf0\x10\x82\xbb\xa3\x8f\x8d",
   'keyId': 7542901657785335835}},
 'operationTime': Timestamp(1765205686, 1)}

________________________________________________________________________________

🔹 Hybrid | Combined | hybrid_personalized
   Params: {'user_id': 1, 'min_avg': 6, 'proximity_radius': 4000, 'limit': 7}
--------------------------------------------------
📋 Result:

,isbn,title,final_score,collab_score,content_score
0,000225056X,The International Garlic Cookbook,5.0,10.0,0.0
1,0002255014,"Leaning, leaning over water: A novel in ten st...",5.0,10.0,0.0
2,0002554062,Shadow Maker: The Life of Gwendolyn Macewen,5.0,10.0,0.0
3,0002554232,The Red Shoes: Margaret Atwood Starting Out,5.0,10.0,0.0
4,0004334787,"Collins-Robert French-English, English-French ...",5.0,10.0,0.0
5,0004704746,Complete Works of William Shakespeare: The Ale...,5.0,10.0,0.0
6,0006485200,The Piano Man's Daughter,5.0,10.0,0.0

🧠 Explain Plan:
[Left_MySQL]:

,id,select_type,table,type,possible_keys,key,key_len,ref,rows,Extra
0,1,PRIMARY,<derived5>,ALL,None,None,None,None,266912,Using temporary; Using filesort
1,5,DERIVED,users,const,PRIMARY,PRIMARY,4,const,1,Using temporary; Using filesort
2,5,DERIVED,b,ALL,PRIMARY,None,None,None,265512,
3,5,DERIVED,r,ref,"PRIMARY,isbn",isbn,42,bookrec.b.isbn,3,Using index condition; Using where
4,5,DERIVED,u,eq_ref,PRIMARY,PRIMARY,4,bookrec.r.user_id,1,Using where
5,7,UNION,<subquery8>,ALL,distinct_key,None,None,None,100,Using temporary; Using filesort
6,7,UNION,r,ref,"PRIMARY,isbn",PRIMARY,4,demo_neighbors.user_id,14,Using where
7,7,UNION,b,eq_ref,PRIMARY,PRIMARY,42,bookrec.r.isbn,1,
8,8,MATERIALIZED,<derived4>,ALL,None,None,None,None,100,
9,4,DERIVED,users,const,PRIMARY,PRIMARY,4,const,1,
10,4,DERIVED,u,ALL,PRIMARY,None,None,None,276061,Using where

[Right_Mongo]:

{'users_profiles': {'explainVersion': '1',
  'stages': [{'$cursor': {'queryPlanner': {'namespace': '68e39feadeb4b70ed33f9ebc_bookrec.users_profiles',
      'parsedQuery': {'_id': {'$eq': 1}},
      'indexFilterSet': False,
      'queryHash': '29E43E3B',
      'planCacheShapeHash': '29E43E3B',
      'planCacheKey': '1D3B2C31',
      'optimizationTimeMillis': 0,
      'maxIndexedOrSolutionsReached': False,
      'maxIndexedAndSolutionsReached': False,
      'maxScansToExplodeReached': False,
      'prunedSimilarIndexes': False,
      'winningPlan': {'isCached': False,
       'stage': 'PROJECTION_DEFAULT',
       'transformBy': {'preferences': 1, 'profile.mean_rating': 1, '_id': 0},
       'inputStage': {'stage': 'IDHACK'}},
      'rejectedPlans': []}}},
   {'$addFields': {'preferences': {'pref_authors_arr': {'$split': [{'$ifNull': ['$preferences.pref_authors',
          {'$const': ''}]},
        {'$const': ','}]},
      'pref_subgenres_arr': {'$split': [{'$ifNull': ['$preferences.pref_subgenres',
          {'$const': ''}]},
        {'$const': ','}]},
      'pref_publishers_arr': {'$split': [{'$ifNull': ['$preferences.pref_publisher',
          {'$const': ''}]},
        {'$const': ','}]},
      'pref_years_arr': {'$split': [{'$ifNull': ['$preferences.pref_pub_year',
          {'$const': ''}]},
        {'$const': ','}]}}}},
   {'$lookup': {'from': 'books_metadata',
     'as': 'recs',
     'let': {'p_sub': '$preferences.pref_subgenres_arr',
      'p_authors': '$preferences.pref_authors_arr',
      'p_publishers': '$preferences.pref_publishers_arr',
      'p_years': '$preferences.pref_years_arr',
      'p_avg_rating': {'$ifNull': ['$profile.mean_rating', {'$const': 0}]}},
     'pipeline': [{'$match': {'$expr': {'$and': [{'$or': [{'$in': ['$extra_metadata.author',
              '$$p_authors']},
            {'$in': ['$extra_metadata.publisher', '$$p_publishers']},
            {'$in': [{'$toString': '$extra_metadata.publication_year'},
              '$$p_years']}]},
          {'$gte': ['$rating_metrics.r_avg', '$$p_avg_rating']}]}}},
      {'$addFields': {'content_score': {'$add': [{'$ifNull': ['$rating_metrics.rating_score',
            0]},
          {'$cond': [{'$cond': [{'$isArray': '$extra_metadata.subgenres'},
              {'$gt': [{'$size': {'$setIntersection': ['$extra_metadata.subgenres',
                   '$$p_sub']}},
                0]},
              {'$in': ['$extra_metadata.subgenres', '$$p_sub']}]},
            2.0,
            0.0]},
          {'$cond': [{'$in': ['$extra_metadata.author', '$$p_authors']},
            3.0,
            0.0]},
          {'$cond': [{'$in': ['$extra_metadata.publisher', '$$p_publishers']},
            1.0,
            0.0]},
          {'$cond': [{'$in': [{'$toString': '$extra_metadata.publication_year'},
              '$$p_years']},
            1.0,
            0.0]},
          {'$ifNull': ['$popularity_metrics.popularity', 0]}]}}},
      {'$sort': {'content_score': -1}},
      {'$limit': 7}],
     'unwinding': {'preserveNullAndEmptyArrays': False}}},
   {'$project': {'isbn': '$recs._id',
     'content_score': '$recs.content_score',
     'title': '$recs.title',
     '_id': False}}],
  'queryShapeHash': '77A2AC8A613ECA75AA2C3891F637E9CF738C87117C108ACE62CDFE0DE6CC5CFD',
  'serverInfo': {'host': 'atlas-viol3m-shard-00-01.7rpsn.mongodb.net',
   'port': 27000,
   'version': '8.0.16',
   'gitVersion': 'ba70b6a13fda907977110bf46e6c8137f5de48f6'},
  'serverParameters': {'internalQueryFacetBufferSizeBytes': 104857600,
   'internalQueryFacetMaxOutputDocSizeBytes': 104857600,
   'internalLookupStageIntermediateDocumentMaxSizeBytes': 16793600,
   'internalDocumentSourceGroupMaxMemoryBytes': 104857600,
   'internalQueryMaxBlockingSortMemoryUsageBytes': 33554432,
   'internalQueryProhibitBlockingMergeOnMongoS': 0,
   'internalQueryMaxAddToSetBytes': 104857600,
   'internalDocumentSourceSetWindowFieldsMaxMemoryBytes': 104857600,
   'internalQueryFrameworkControl': 'trySbeRestricted',
   'internalQueryPlannerIgnoreIndexWithCollationForRegex': 1},
  'command': {'aggregate': 'users_profiles',
   'pipeline': [{'$match': {'_id': 1}},
    {'$addFields': {'preferences.pref_authors_arr': {'$split': [{'$ifNull': ['$preferences.pref_authors',
          '']},
        ',']},
      'preferences.pref_subgenres_arr': {'$split': [{'$ifNull': ['$preferences.pref_subgenres',
          '']},
        ',']},
      'preferences.pref_publishers_arr': {'$split': [{'$ifNull': ['$preferences.pref_publisher',
          '']},
        ',']},
      'preferences.pref_years_arr': {'$split': [{'$ifNull': ['$preferences.pref_pub_year',
          '']},
        ',']}}},
    {'$lookup': {'from': 'books_metadata',
      'let': {'p_sub': '$preferences.pref_subgenres_arr',
       'p_authors': '$preferences.pref_authors_arr',
       'p_publishers': '$preferences.pref_publishers_arr',
       'p_years': '$preferences.pref_years_arr',
       'p_avg_rating': {'$ifNull': ['$profile.mean_rating', 0]}},
      'pipeline': [{'$match': {'$expr': {'$and': [{'$or': [{'$in': ['$extra_metadata.author',
               '$$p_authors']},
             {'$in': ['$extra_metadata.publisher', '$$p_publishers']},
             {'$in': [{'$toString': '$extra_metadata.publication_year'},
               '$$p_years']}]},
           {'$gte': ['$rating_metrics.r_avg', '$$p_avg_rating']}]}}},
       {'$addFields': {'content_score': {'$add': [{'$ifNull': ['$rating_metrics.rating_score',
             0]},
           {'$cond': [{'$cond': [{'$isArray': '$extra_metadata.subgenres'},
               {'$gt': [{'$size': {'$setIntersection': ['$extra_metadata.subgenres',
                    '$$p_sub']}},
                 0]},
               {'$in': ['$extra_metadata.subgenres', '$$p_sub']}]},
             2.0,
             0.0]},
           {'$cond': [{'$in': ['$extra_metadata.author', '$$p_authors']},
             3.0,
             0.0]},
           {'$cond': [{'$in': ['$extra_metadata.publisher', '$$p_publishers']},
             1.0,
             0.0]},
           {'$cond': [{'$in': [{'$toString': '$extra_metadata.publication_year'},
               '$$p_years']},
             1.0,
             0.0]},
           {'$ifNull': ['$popularity_metrics.popularity', 0]}]}}},
       {'$sort': {'content_score': -1}},
       {'$limit': 7}],
      'as': 'recs'}},
    {'$unwind': '$recs'},
    {'$project': {'isbn': '$recs._id',
      'content_score': '$recs.content_score',
      'title': '$recs.title',
      '_id': 0}}],
   'explain': True,
   'apiVersion': '1',
   'lsid': {'id': Binary(b'\xd33\xa3y=\xb0@5\x89hW\xcb\xe2\x9ct\x9f', 4)},
   '$clusterTime': {'clusterTime': Timestamp(1765205693, 1),
    'signature': {'hash': b'x\x97\xf5\xd5\xdc\xb4\x88\\l\xb4\xbb\xef\x0f\xc5\x02k%u\x82\xc4',
     'keyId': 7542901657785335835}},
   '$db': '68e39feadeb4b70ed33f9ebc_bookrec',
   'maxTimeMS': 300000,
   'comment': {'AtlasProxyDBPrefix': '68e39feadeb4b70ed33f9ebc_',
    'AtlasProxyAppName': 'Cluster0',
    'AtlasProxyClientMetadata': {'driver': {'name': 'PyMongo|c',
      'version': '4.15.3'},
     'os': {'type': 'Linux',
      'name': 'Linux',
      'architecture': 'x86_64',
      'version': '6.17.4-arch2-1'},
     'platform': 'CPython 3.13.7.final.0',
     'application': {'name': 'Cluster0'},
     'clientTLSVersion': 'TLS 1.3'}}},
  'ok': 1.0,
  '$clusterTime': {'clusterTime': Timestamp(1765205693, 1),
   'signature': {'hash': b'x\x97\xf5\xd5\xdc\xb4\x88\\l\xb4\xbb\xef\x0f\xc5\x02k%u\x82\xc4',
    'keyId': 7542901657785335835}},
  'operationTime': Timestamp(1765205693, 1)}}

[Strategy]:

  Join_Type                               Keys                          Logic
0     OUTER  {'left': 'isbn', 'right': 'isbn'}  Pandas Application-Side Merge

________________________________________________________________________________

**Notes:**
- When the recommendations are run several times, for the same user, the database management system will use cached results/ materialized views, so the execution will be faster!  
- Purely MongoDB recommendations dnon't include book-titles in the results, as they are not stored in MongoDB, ate the momment.